### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by CosminPerRam** [Andrei6700/online-shop#1]
A README would be really great to link viewers to a short description of this project.
A README could (or should?) contain points about:
- What, Why and How come the projects idea came to be or whats its purpose.
- Technical details (what technologies does this use?).
- Project setup (I want to run this project on my machine, what do I need and what are the steps?)

**Comment by Andrei6700** [comment]
I will add a ``Readme.md'' file soon. I was planning to add it when I finish this project. I can't give an exact date when I will add it, but I will still keep in mind those points you mentioned above.

**Comment by CosminPerRam** [comment]
bump

**Comment by Andrei6700** [comment]
Like I said I'll add it and today was the day! If you have any queries on the part of running the project or discussing what I could add, please open an issue first.
