### ISSUE TITLE
Edit page title and metadata.

### ISSUE THREAD

**Issue by CosminPerRam** [Andrei6700/online-shop#3]
The [public/index.html](https://github.com/Andrei6700/online-shop/blob/master/public/index.html) file contains a `<Title>` tag which is set to the default `React App` value, this actually goes the same for the 4th `<meta>` tag.

**Comment by Andrei6700** [comment]
Yes, I noticed that```<title>React App</title>``` was set to default together with ```<meta>```, now I made a commit about it..
