### ISSUE TITLE
Add site icon and remove invalid link

### ISSUE THREAD

**Issue by CosminPerRam** [Andrei6700/online-shop#4]
There is no `favicon.ico` file in `public` :(
Also, in `public/index.html`, there is this tag that is invalid: `<link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />` because `logo192.png` is missing.

**Comment by Andrei6700** [comment]
Yes, this was omitted by me when I made this website.
Now I made a new commit with its update.
