### ISSUE TITLE
Use `children` prop in content

### ISSUE THREAD

**Issue by CosminPerRam** [Andrei6700/online-shop#6]
[src/UI/page-layout/content.js](https://github.com/Andrei6700/online-shop/blob/master/src/UI/page-layout/content.js)
has:
```js
import React from "react"
import {ContentChildrens} from "../page-setup/ContentChildrens"

export const Content=()=>{
    return (
        <div class="content">
            <div className="title">Magazin Online de Tancuri
            <hr className="hr-title"/>
            </div>
            <ContentChildrens/>
        </div>
    )
}
```
Using the `children` react prop would be much better and would yield nicer code readability, some docs about it here: [Legacy React Docs](https://legacy.reactjs.org/docs/composition-vs-inheritance.html).

**Comment by CosminPerRam** [comment]
Actually, the `Filters` component does the same thing.

**Comment by CosminPerRam** [comment]
bump

**Comment by Andrei6700** [comment]
Hello! Now I've noticed I'd rather use that `children` prop. I updated the project and the cart in [src/UI/page-layout/content.js](https://github.com/Andrei6700/online-shop/blob/master/src/UI/page-layout/content.js) looks like this :

  ```js
import React from "react";
import { ContentChildrens } from "../page-setup/ContentChildrens";

export const Content = () => {
  return (
    <div>
      <ContentChildrens />
    </div>
  );
};

```

**Comment by CosminPerRam** [comment]
I still dont see any usage of the `children` prop anywhere.
[Here](https://codeburst.io/a-quick-intro-to-reacts-props-children-cb3d2fce4891) are some examples if you are confused about what I'm talking about.

**Comment by Andrei6700** [comment]
Yes...now I understand how to do it, sometimes I'm harder to figure out :(( 
This is the new update to [src/UI/page-layout/content.js](https://github.com/Andrei6700/online-shop/blob/master/src/UI/page-layout/content.js):
```js
import React from "react";
import { ContentChildrens } from "../page-setup/ContentChildrens";
import { tankData } from "../page-setup/tank-data/TankData";

export const Content = () => {
  return (
    <div>
      <ContentChildrens tank={tankData} />
    </div>
  );
};
  
```
