### ISSUE TITLE
[CI] Deploy to Vercel.

### ISSUE THREAD

**Issue by CosminPerRam** [Andrei6700/online-shop#7]
A live demo would be great to see.
[Vercel](https://vercel.com/) offers a free tier to host sites such as this one.
The setup is very easy, you could probably deploy it without taking a look at tutorials.
What do you think? If you do want to deploy it and you encounter issues, I could help happily.

**Comment by Andrei6700** [comment]
Hi! So far I haven't heard of Vercel, but I'm glad you told me about it. After a little documentation, I was able to add it. The link is in the documentation.

**Comment by CosminPerRam** [comment]
Woah, thats great, thanks.
